language: python
python:
    - "3.8"

services:
    - docker

before_scripts: pip install docker-compose

scripts:
    - docker-compose run app sh -c "coverage run --source='.' manage.py test && flake8"
    - docker-compose run --rm app sh -c "coverage report -m"