# Generated by Django 3.0.7 on 2020-06-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200608_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='products',
            field=models.ManyToManyField(to='shop.Product'),
        ),
    ]
