# Generated by Django 3.0.7 on 2020-06-08 12:41

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200608_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to=shop.models.product_image_file_path),
        ),
    ]
