# Generated by Django 3.0.7 on 2020-06-27 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20200623_0959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Shop Address'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Shop Products'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name_plural': 'Shop'},
        ),
    ]
