# Generated by Django 3.0.7 on 2020-06-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='completed',
            field=models.BooleanField(default=True),
        ),
    ]
